[platformio]
default_envs = esp32dev

[env]
framework = arduino
board_build.flash_mode = dout
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB0

[env:esp32dev]
board = esp32dev
platform =
    https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
;platform_packages =
    ;framework-espidf @ https://github.com/pioarduino/esp-idf/releases/download/v6.1.0/esp-idf-v6.1.0.tar.xz
;build_unflags =
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0 ;; this flag is mandatory for "classic ESP32" when building with arduino-esp32 >=2.0.3
lib_deps =
    https://github.com/pschatzmann/ESP32-A2DP.git#v1.8.11
    https://github.com/pschatzmann/arduino-audio-tools.git#v1.2.6
    ; old https://github.com/pschatzmann/arduino-libsbc.git#v1.0.0
    ; old https://github.com/pschatzmann/arduino-libhelix.git#v0.9.4
    ;https://github.com/pschatzmann/codec-sbc.git#v1.0.0
    ;https://github.com/pschatzmann/codec-helix.git#v0.9.4
    duinowitchery/hd44780@1.3.2
    mathertel/OneButton@2.6.2
board_build.partitions = min_spiffs_4MB.csv
board_build.filesystem = spiffs
board_build.flash_mode = dio
upload_speed = 460800
